import React from 'react'

export const metadata = {
    title: 'DASHBOARSD',
    description: 'Generated by RPL',
  }

function DashboardLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return(
    <div>
        DashboardLayout
    {children}
    </div>
  )
}

export default DashboardLayout